import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire,Module} from 'node:module';import path from 'node:path';
const require=createRequire(import.meta.url),ts=require('../storefront-source/node_modules/typescript');
function load(){const file=path.resolve('storefront-source/src/always-on/connection.ts'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));m._compile(ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,file);return m.exports}
const memory=new Map();globalThis.sessionStorage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};
const reply=d=>new Response(JSON.stringify(d),{status:200,headers:{'Content-Type':'application/json'}});
test('guest bootstrap is shared and requests use the dev session',async()=>{memory.clear();const calls=[];globalThis.fetch=async(url,opts)=>{calls.push({url,opts});return reply(url.endsWith('/guest')?{access_token:'synthetic-test-token',refresh_token:'synthetic-refresh',expires_in:3600}:{ok:true})};const c=load();await Promise.all([c.request('/v1/avatars'),c.request('/v2/user')]);assert.equal(calls.filter(x=>x.url.endsWith('/guest')).length,1);assert(calls.every(x=>x.url.startsWith('https://api.dev.spreeai.com/')));assert.equal(calls[1].opts.headers.Authorization,'Bearer synthetic-test-token')});
test('invalid measurements cannot call a backend or save a profile',async()=>{memory.clear();let calls=0;globalThis.fetch=async()=>{calls++;throw Error('unexpected')};const c=load();await assert.rejects(c.saveMeasurements({height:NaN,weight:70}),/height/);await assert.rejects(c.saveMeasurements({height:170,weight:0}),/weight/);assert.equal(calls,0);assert.equal(c.currentProfile().identity,null)});
test('completion after sign-out cannot apply data to a new session',async()=>{memory.clear();let resolve;globalThis.fetch=async url=>url.endsWith('/guest')?reply({access_token:'fake',expires_in:3600}):new Promise(r=>resolve=r);const c=load();await c.ensureSession();const pending=c.request('/v2/user');await new Promise(r=>setImmediate(r));c.clearConnectedSession();resolve(reply({first_name:'Previous user'}));await assert.rejects(pending,/session changed/);assert.equal(c.currentProfile().identity,null)});
test('photo upload uses official multipart fields',async()=>{memory.clear();let body;globalThis.fetch=async(url,opts)=>{if(url.endsWith('/guest'))return reply({access_token:'fake',expires_in:3600});body=opts.body;assert.equal(opts.headers['Content-Type'],undefined);return reply({id:'fixture',url:'https://example.invalid/photo'})};const c=load();await c.uploadPhoto(new File(['fixture'],'fixture.png',{type:'image/png'}));assert(body instanceof FormData);assert.equal(body.get('source'),'web-sdk');assert.equal(body.get('is_uploaded'),'true');assert.equal(body.get('user_image').name,'fixture.png')});
test('sizing without a chart terminates instead of spinning forever',async()=>{memory.clear();globalThis.fetch=async url=>reply(url.endsWith('/guest')?{access_token:'fake',expires_in:3600}:url.includes('/user-assets/')?{request_id:'fixture',result:'2006'}:{request_id:'fixture'});const c=load();const result=await c.sizing('dress',{height:170,weight:65,bodyType:'Feminine'},new AbortController().signal);assert.equal(result.result,'2006');assert.equal(result.sizing,undefined)});
