import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire,Module} from 'node:module';import path from 'node:path';
const require=createRequire(import.meta.url),ts=require('../storefront-source/node_modules/typescript');
function load(name='connection'){const file=path.resolve('storefront-source/src/always-on/'+name+'.ts'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));const original=m.require.bind(m);m.require=id=>['./history','./loading','./preview-cache'].includes(id)?load(id.slice(2)):original(id);m._compile(ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,file);return m.exports}
const memory=new Map();globalThis.sessionStorage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
const reply=d=>new Response(JSON.stringify(d),{status:200,headers:{'Content-Type':'application/json'}});
test('guest bootstrap is shared and requests use the dev session',async()=>{memory.clear();const calls=[];globalThis.fetch=async(url,opts)=>{calls.push({url,opts});return reply(url.endsWith('/guest')?{access_token:'synthetic-test-token',refresh_token:'synthetic-refresh',expires_in:3600}:{ok:true})};const c=load();await Promise.all([c.request('/v1/avatars'),c.request('/v2/user')]);assert.equal(calls.filter(x=>x.url.endsWith('/guest')).length,1);assert(calls.every(x=>x.url.startsWith('https://api.dev.spreeai.com/')));assert.equal(calls[1].opts.headers.Authorization,'Bearer synthetic-test-token')});
test('invalid measurements cannot call a backend or save a profile',async()=>{memory.clear();let calls=0;globalThis.fetch=async()=>{calls++;throw Error('unexpected')};const c=load();await assert.rejects(c.saveMeasurements({height:NaN,weight:70}),/height/);await assert.rejects(c.saveMeasurements({height:170,weight:0}),/weight/);assert.equal(calls,0);assert.equal(c.currentProfile().identity,null)});
test('completion after sign-out cannot apply data to a new session',async()=>{memory.clear();let resolve;globalThis.fetch=async url=>url.endsWith('/guest')?reply({access_token:'fake',expires_in:3600}):new Promise(r=>resolve=r);const c=load();await c.ensureSession();const pending=c.request('/v2/user');await new Promise(r=>setImmediate(r));c.clearConnectedSession();resolve(reply({first_name:'Previous user'}));await assert.rejects(pending,/session changed/);assert.equal(c.currentProfile().identity,null)});
test('photo upload uses official multipart fields',async()=>{memory.clear();let body;globalThis.fetch=async(url,opts)=>{if(url.endsWith('/guest'))return reply({access_token:'fake',expires_in:3600});body=opts.body;assert.equal(opts.headers['Content-Type'],undefined);return reply({id:'fixture',url:'https://example.invalid/photo'})};const c=load();await c.uploadPhoto(new File(['fixture'],'fixture.png',{type:'image/png'}));assert(body instanceof FormData);assert.equal(body.get('source'),'web-sdk');assert.equal(body.get('is_uploaded'),'true');assert.equal(body.get('user_image').name,'fixture.png')});
test('sizing without a chart terminates instead of spinning forever',async()=>{memory.clear();globalThis.fetch=async url=>reply(url.endsWith('/guest')?{access_token:'fake',expires_in:3600}:url.includes('/user-assets/')?{request_id:'fixture',result:'2006'}:{request_id:'fixture'});const c=load();const result=await c.sizing('dress',{height:170,weight:65,bodyType:'Feminine'},new AbortController().signal);assert.equal(result.result,'2006');assert.equal(result.sizing,undefined)});

test('production and development credentials are isolated',async()=>{memory.clear();const calls=[];globalThis.fetch=async(url,opts)=>{calls.push({url,opts});return reply(url.endsWith('/guest')?{access_token:url.includes('api.dev.')?'dev-only':'prod-only',expires_in:3600}:{garments:[]})};const c=load();await Promise.all([c.request('/v3/protea/garments'),c.productionRequest('/v3/protea/garments')]);for(const call of calls.filter(c=>!c.url.endsWith('/guest')))assert.equal(call.opts.headers.Authorization,call.url.includes('api.dev.')?'Bearer dev-only':'Bearer prod-only')});
test('production request completing after signout is rejected',async()=>{memory.clear();let resolve;globalThis.fetch=async url=>url.endsWith('/guest')?reply({access_token:'fake',expires_in:3600}):new Promise(r=>resolve=r);const c=load();const pending=c.productionRequest('/v3/protea/garments');await new Promise(r=>setImmediate(r));c.clearConnectedSession();resolve(reply({garments:[]}));await assert.rejects(pending,/session changed/)});

test('shopping history deduplicates repeated results, records size changes and clears on signout',()=>{memory.clear();const h=load('history');const item={id:'front-1',kind:'tryon',identityId:'twin-fixture',identityName:'Fixture',pieces:[{id:'dress',name:'Dress',image:'https://example.invalid/dress'}],images:['https://example.invalid/result']};h.recordHistory(item);h.recordHistory(item);h.recordHistory({...item,id:'size-S',kind:'sizing',size:'S'});assert.equal(JSON.parse(memory.get('spree-shopping-history-v1')).length,2);const c=load();c.clearConnectedSession();assert.deepEqual(JSON.parse(memory.get('spree-shopping-history-v1')),[])});

test('deleting activity persists across reload and excludes other perspectives',()=>{memory.clear();const h=load('history');const item={id:'tryon-one',kind:'tryon',identityId:'one',identityName:'One',pieces:[],images:[]};h.recordHistory(item);h.recordHistory({...item,id:'size-one',kind:'sizing'});h.recordHistory({...item,id:'compare-two',kind:'comparison',identityId:'two'});h.deleteHistory(item.id);h.recordHistory(item);assert.equal(JSON.parse(memory.get('spree-shopping-history-v1')).length,2);const fresh=load('history');fresh.recordHistory(item);assert.equal(JSON.parse(memory.get('spree-shopping-history-v1')).length,2);fresh.clearIdentityHistory('one');assert.deepEqual(JSON.parse(memory.get('spree-shopping-history-v1')).map(x=>x.identityId),['two'])});
test('loading rail remains active until concurrent operations finish',()=>{const l=load('loading');const finishA=l.beginLoading(),finishB=l.beginLoading();assert.equal(l.loadingCount(),2);finishA();finishA();assert.equal(l.loadingCount(),1);finishB();assert.equal(l.loadingCount(),0)});
test('size-specific renders send selected size and the same recommendation anchor',async()=>{memory.clear();const requests=[];globalThis.fetch=async(url,opts)=>{if(url.endsWith('/guest'))return reply({access_token:'fixture',expires_in:3600});if(url.endsWith('/tryon')){const body=JSON.parse(opts.body);requests.push({url,body});return reply({request_id:'size-'+body.size})}return reply({status:'COMPLETE',image:{url:'https://example.invalid/'+url.split('/').pop()}})};const c=load(),identity={id:'twin-fixture'};const baseline=await c.render('skirt',identity,new AbortController().signal,'front','6','6');const alternate=await c.render('skirt',identity,new AbortController().signal,'front','8','6');assert(requests.every(r=>r.url.endsWith('/v3.1/store-experience/tryon')));assert.deepEqual(requests.map(r=>[r.body.size,r.body.base_size]),[['6','6'],['8','6']]);assert.notEqual(baseline.image.url,alternate.image.url)});
