import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire,Module} from 'node:module';import path from 'node:path';
const require=createRequire(import.meta.url),ts=require('../storefront-source/node_modules/typescript'),file=path.resolve('storefront-source/src/always-on/stylist-conversation.ts'),m=new Module(file);m._compile(ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);const {emptyBrief,understand,selectPieces,completePieces}=m.exports;
const p=(id,category,price=100,currency='USD')=>({id,name:id,category,price,currency,description:'',color:'Black',environment:'dev'});
test('conversation remembers occasion and parses preference and budget updates',()=>{let b=understand('I have a wedding to go to',emptyBrief);b=understand('Understated dresses under $1,000, no white',b);assert.equal(b.occasion,'A wedding');assert.equal(b.direction,'Understated');assert.equal(b.category,'Dresses');assert.equal(b.budget,1000);assert.deepEqual(b.avoid,['white']);assert.equal(understand('No budget limit',b).budget,null);assert.equal(emptyBrief.occasion,'')});
test('recommendations enforce category, budget currency, and exclusion constraints',()=>{const b={...emptyBrief,category:'Dresses',budget:500,avoid:['white']};const catalog=[p('black','Dresses'),p('white','Dresses'),p('expensive','Dresses',1000),p('euro','Dresses',100,'EUR'),p('shirt','Shirts')];assert.deepEqual(selectPieces(catalog,b).map(x=>x.id),['black'])});
test('outfits retain the chosen anchor and do not mix backend environments',()=>{const a=p('dress','Dresses'),other={...p('prod-bag','Accessories'),environment:'prod'},bag=p('bag','Accessories');assert.deepEqual(completePieces([a,other,bag],a,emptyBrief).map(x=>x.id),['dress','bag'])});
test('empty matches never silently ignore a budget',()=>{assert.deepEqual(selectPieces([p('gown','Dresses',2000)],{...emptyBrief,budget:20}),[])});

test('every offered occasion starts a brief',()=>{for(const phrase of ['A wedding','An evening out','A getaway','Everyday','Work'])assert.ok(understand(phrase,emptyBrief).occasion,phrase)});
test('every recorded speech key has a valid local WAV asset',()=>{const speechFile=path.resolve('storefront-source/src/always-on/stylist-speech.ts'),speechModule=new Module(speechFile);speechModule._compile(ts.transpileModule(readFileSync(speechFile,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,speechFile);for(const key of Object.keys(speechModule.exports.stylistSpeech)){const data=readFileSync('online/media/stylist-celine/'+key+'.wav');assert.equal(data.toString('ascii',0,4),'RIFF');assert.equal(data.toString('ascii',8,12),'WAVE');assert.ok(data.length>10000)}});
