/** Local connected preview. For hosted deployments mount the same exact proxy routes server-side. */
import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.mp4':'video/mp4','.woff2':'font/woff2'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname.startsWith('/api/')){if(req.method!=='POST'||!/^\/api\/size-recommendation\/garment\/[A-Za-z0-9_-]+(?:\/fit)?$/.test(url.pathname)){res.writeHead(404);res.end();return}if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`){res.writeHead(403);res.end();return}if(!/^Bearer [A-Za-z0-9_.-]+$/.test(req.headers.authorization||'')){res.writeHead(401);res.end();return}let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>65536){res.writeHead(413);res.end();return}chunks.push(chunk)}const upstream=await fetch('https://demo-store.dev.spreeai.com'+url.pathname,{method:'POST',headers:{'Content-Type':'application/json',Authorization:req.headers.authorization},body:Buffer.concat(chunks),signal:AbortSignal.timeout(30000)});res.writeHead(upstream.status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(await upstream.text());return}const relative=decodeURIComponent(url.pathname).replace(/^\/spreeai-always-on-demo\//,'/');let file=path.resolve(root,'.'+relative);if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return}try{if((await stat(file)).isDirectory())file=path.join(file,'index.html')}catch{if(relative.startsWith('/online/'))file=path.join(root,'online/index.html');else throw Error('missing')}const data=await readFile(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(data)}catch{res.writeHead(502,{'Content-Type':'application/json'});res.end(JSON.stringify({message:'The connected service is temporarily unavailable. Please try again.'}))}});
server.listen(8769,'127.0.0.1',()=>console.log('Connected preview: http://127.0.0.1:8769/spreeai-always-on-demo/online/'));
