import {readJourney,togglePiece} from '../../../journey/store.js';
import Journey, {SavePiece, useJourney} from './Journey';
import CheckoutCelebration from './CheckoutCelebration';
import TutorialToggle from './TutorialToggle';
import {useTutorialsEnabled} from './tutorialPreference';
import {useState,useEffect} from 'react';
import type {FormEvent} from 'react';
import {Link,useLocation,useNavigate} from 'react-router';
import * as Dialog from '@radix-ui/react-dialog';
import {products,twins,asset,money,sampleProfile,categories,displayImage,editorialImage} from './data';
import type {Mode,Profile} from './data';
import './style.css';
import Stylist from './Stylist';
import StylistWelcome from './StylistWelcome';
import Gallery from './Gallery';
import FeatureNote from './FeatureNote';
import Guide from './Guide';
const spreeLogo='/spreeai-logo.svg';
import {wardrobe} from './wardrobe';

type Panel='journey'|'checkout'|'developer'|'guide'|'unlock'|'twins'|'signin'|'profile'|'why'|'compare'|'bag'|'stylist'|'saved'|'colors'|'recommendations'|null;
function read<T,>(key:string,fallback:T):T {try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
export default function App(){
 const nav=useNavigate(),location=useLocation();
 const journey=useJourney();
 const [pendingJourneyPiece,setPendingJourneyPiece]=useState('');
 const [mode,setMode]=useState<Mode>(()=>read('ao-mode','out'));
 const [person,setPerson]=useState(()=>read('ao-person',1));
 const [profile,setProfile]=useState<Profile>(()=>read('ao-profile',sampleProfile));
 const tutorialsEnabled=useTutorialsEnabled();
 const [panel,setPanel]=useState<Panel>(()=>location.pathname==='/'||tutorialsEnabled?'guide':null);
 const [step,setStep]=useState(0),[readyKey,setReadyKey]=useState('');
 const [initialMedia,setInitialMedia]=useState('');
 const [mediaOrder,setMediaOrder]=useState<'model'|'personal'>(()=>read('ao-media-order','model'));
 const [measure,setMeasure]=useState({height:profile.height,weight:profile.weight});
 const [search,setSearch]=useState(''),[limit,setLimit]=useState(12),[voice,setVoice]=useState<'director'|'advisor'>(()=>read('ao-voice','director'));
 const [previousPath,setPreviousPath]=useState(location.pathname);
 const [chosenTwin,setChosenTwin]=useState(person),[size,setSize]=useState(''),[filter,setFilter]=useState('All'),[sort,setSort]=useState('featured');
 const [compare,setCompare]=useState<string[]>([]),[bag,setBag]=useState<{id:string,size:string}[]>([]),[toast,setToast]=useState('');
 const [unit,setUnit]=useState('metric'),[photo,setPhoto]=useState(profile.photo),[age,setAge]=useState('adult');
 const [error,setError]=useState('');
 const routePath=location.pathname.replace(/\/$/,'')||'/';
 const product=products.find(p=>routePath===`/product/${p.id}`);
 const account=routePath==='/account';
 const active=mode!=='out';
 const isJourneySample=mode==='personal'&&profile.name==='Alex'&&profile.photo==='sample';
 function startJourney(){switchMode('personal');if(pendingJourneyPiece&&!readJourney().items.some(x=>x.id===pendingJourneyPiece))togglePiece(pendingJourneyPiece);setPendingJourneyPiece('');setPanel('journey')}
 const recommended=product?.category==='Accessories'?'One size':product?.category==='Shoes'?'42':product?.sizes.includes('32')?'32':mode==='personal'?'M':twins[person].size;
 const who=mode==='personal'?profile.name:twins[person].name;
 const generationKey=`${mode}:${person}`;
 const ready=readyKey===generationKey;
 if(previousPath!==location.pathname){setPreviousPath(location.pathname);setInitialMedia('');setSize('');setError('')}
 useEffect(()=>{localStorage.setItem('ao-mode',JSON.stringify(mode));localStorage.setItem('ao-person',JSON.stringify(person));const timer=setTimeout(()=>setReadyKey(generationKey),1250);return()=>clearTimeout(timer)},[mode,person,generationKey]);
 useEffect(()=>{window.scrollTo(0,0)},[location.pathname]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer)},[toast]);
 function open(value:Panel){setError('');if(value==='profile'){setPhoto(profile.photo);setMeasure({height:profile.height,weight:profile.weight});setUnit('metric')}setPanel(value)}
 function close(){setPanel(null);setPendingJourneyPiece('')}
 function switchMode(next:Mode){setMode(next);setInitialMedia('');if(next==='personal'){setProfile(sampleProfile);localStorage.setItem('ao-profile',JSON.stringify(sampleProfile));setPerson(1)}if(next==='twin')setPerson(chosenTwin);setToast(next==='out'?'Signed-out experience':next==='twin'?'AI Twin experience':'Personalized demo profile loaded')}
 function toggleCompare(id:string){setCompare(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id].slice(-2))}
 function compareOpen(){if(!active){open('unlock');return}if(compare.length<2)setCompare([...(compare.length?compare:[product?.id||products[0].id]),products.find(p=>p.id!==(compare[0]||product?.id||products[0].id))!.id]);open('compare')}
 function finishProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);if(age!=='adult'){setError('Personal photo profiles are available to adults in this demo. Please use an AI Twin.');return}if(!photo){setError('Add a photo or use the sample profile to continue.');return}if(!data.get('consent')){setError('Please confirm that you want to enable your visualization profile.');return}const value:Profile={name:String(data.get('name')).trim()||'Alex',height:Number(data.get('height'))*(unit==='imperial'?2.54:1),weight:Number(data.get('weight'))*(unit==='imperial'?0.453592:1),gender:String(data.get('gender')),fit:String(data.get('fit')),photo,consent:true};setProfile(value);localStorage.setItem('ao-profile',JSON.stringify({...value,photo:photo==='sample'?'sample':''}));setMode('personal');setPerson(1);close();setToast('Your profile is connected. Personalization is now on.')}
 const photoView=(row:number,idx=person,className='')=><img className={className} src={asset(idx,row)} alt={`${twins[idx].name}, ${row===1||row===3?'back':'front'} view in ${row<2?'leather biker jacket':'burgundy knit polo'}`} />;
 const badge=<span className="powered">✧ Powered by SPREEAI</span>;
 const previewNotice=<p className="fine">Illustrative local preview. Generated sample imagery; no live try-on or fit inference.</p>;
 const recommendationRail=(title:string)=><section className="recommendation-section"><div className="section-head"><div><p className="eyebrow">SELECTED BY THE SPREEAI CREATIVE STUDIO</p><h2>{title}</h2></div><button className="text-link" onClick={()=>open('stylist')}>Meet your stylist ↗</button></div><p>{active?`A considered edit, already on ${mode==='personal'?'you':who}. Your perspective follows you here, too.`:'The brand’s edit becomes your edit. Sign into your account to see these recommendations on you.'}</p><FeatureNote panel="recommendations" inline/><div className="recommendation-rail">{[...products.filter(p=>p.preview==='core'||p.preview==='imported'),...products.filter(p=>p.preview==='look')].filter(p=>p.id!==product?.id).slice(0,5).map(p=><article key={p.id}><Link to={`/product/${p.id}`}><img loading="lazy" src={editorialImage(p,person,active)} alt={`${p.name}${active?' on '+who:''}`}/><span className="rail-tag">{active?'On '+(mode==='personal'?'you · sample':who):'CURATED FOR YOU'}</span><h3>{p.name}</h3></Link><p>{money(p.price)}</p><button className="text-link" onClick={()=>toggleCompare(p.id)}>{compare.includes(p.id)?'✓ In your edit':'+ Compare'}</button></article>)}</div></section>;
 return <>
  <a className="skip" href="#content">Skip to content</a>
  <div className="announcement">A new perspective on getting dressed <span>ALWAYS ON · SPREEAI</span></div>
  <header>
   <div className="header-side"><button aria-label="Guide" onClick={()=>{setStep(0);open('guide')}}>✧ <span>Guide</span></button></div>
   <Link to="/" className="wordmark" aria-label="SPREEAI home"><img src={spreeLogo} alt="SPREEAI"/><span>THE ALWAYS ON DEMO</span></Link>
   <div className="header-side right"><button onClick={()=>nav('/account')} aria-label="My Account"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/></svg><span>My Account</span></button><button onClick={()=>open('bag')} aria-label={`Shopping bag, ${bag.length} items`}><svg viewBox="0 0 24 24"><path d="M5 7h14l1 14H4L5 7Z M9 8V5a3 3 0 0 1 6 0v3"/></svg><span>({bag.length})</span></button></div>
  </header>
  <nav className="mainnav" aria-label="Collection navigation"><Link to="/" onClick={()=>setFilter('All')}>The collection</Link>{['Shirts','Tops','Bottoms','Outerwear','Accessories'].map(c=><Link key={c} to="/#collection" onClick={()=>{setFilter(c);setLimit(12)}}>{c}</Link>)}<button onClick={()=>open('stylist')}>AI stylist</button><button onClick={()=>open('saved')}>Saved looks</button><button onClick={()=>open('journey')}>My edit {journey.items.length>0&&`(${journey.items.length})`}</button><button onClick={compareOpen}>Compare {compare.length>0&&`(${compare.length})`}</button></nav>
  <main id="content">
  {!product&&!account&&<>

   <section className="status-strip"><div><img className="sa-mark" src="/sa-logo.svg" alt="SA"/><span>{mode==='out'?'It starts with your SPREEAI account.':mode==='twin'?`The collection, on ${who}.`:`Welcome back, ${who}. Your perspective is on.`}<small>{mode==='out'?'Sign in, add your photo and fit details once. The rest fits into the way you shop.':mode==='twin'?`${twins[person].height} cm · ${twins[person].weight} kg · Sample size ${twins[person].size}`:`${Math.round(profile.height)} cm · ${Math.round(profile.weight)} kg · Sample size M · ${profile.fit} fit`}</small></span></div><button onClick={()=>open(mode==='out'?'signin':mode==='twin'?'twins':'profile')}>{mode==='out'?'Sign in to make it yours':mode==='twin'?'Change AI Twin':'Your profile'} <span>↗</span></button></section>
   <section id="collection" className="collection"><div className="section-head"><div><p className="eyebrow">READY-TO-WEAR</p><h2>The considered edit</h2></div><p>{products.length} pieces. One connected experience.</p></div>
    <FeatureNote panel="collection" inline/><label className="catalog-search">Find a piece<input type="search" aria-label="Search collection" placeholder="Search shirts, denim, a favorite piece…" value={search} onChange={e=>{setSearch(e.target.value);setLimit(12)}}/></label><div className="filters"><div>{categories.map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>{setFilter(x);setLimit(12)}}>{x}</button>)}</div><label>Sort <select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>
    <div className="product-grid">{products.filter(p=>(filter==='All'||filter===p.category)&&p.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:sort==='high'?b.price-a.price:0).slice(0,limit).map((p,i)=><article className="product-card" key={p.id}>
     <Link className={`product-image ${active&&mediaOrder==='personal'&&!ready?'loading':''}`} to={`/product/${p.id}`}><img loading="lazy" src={active&&mediaOrder==='personal'?editorialImage(p,person,active):p.image} alt={active&&p.preview&&mediaOrder==='personal'?`${who} wearing ${p.name}, sample visualization`:p.name}/><img className="hover-model" loading="lazy" src={displayImage(p,person,false)} alt={`${p.name} on the collection model`}/><span className="image-tag">{active&&p.preview&&mediaOrder==='personal'?(ready?`${mode==='personal'?'On you · sample':`On ${who}`}`:'Preparing your view…'):'THE EDIT'}</span><span className="discover">Discover the piece ↗</span></Link>
     <div className="product-info"><div><Link to={`/product/${p.id}`}><h3>{p.name}</h3></Link><p>{p.color} · {p.category}</p></div><span>{money(p.price)}</span></div>
     <div className="card-bottom"><span>{active&&p.preview?`${mode==='personal'?'Your views':'Twin views'} ready`:`${p.sizes.length} ${p.sizes.length===1?'size':'sizes'} available`}</span><button aria-pressed={compare.includes(p.id)} onClick={()=>toggleCompare(p.id)}>{compare.includes(p.id)?'✓ Added to edit':'+ Compare'}</button></div>
     <SavePiece id={p.id} isSample={isJourneySample} onStart={()=>{setPendingJourneyPiece(p.id);open('journey')}}/>
     {i===0&&<div className="card-note">{badge}<span>{active?'A familiar face. A fresh perspective.':'Personal style starts with your perspective.'}</span></div>}
    </article>)}</div><div className="catalog-more"><p>{products.filter(p=>(filter==='All'||p.category===filter)&&p.name.toLowerCase().includes(search.toLowerCase())).length} matching pieces</p>{limit<products.filter(p=>(filter==='All'||p.category===filter)&&p.name.toLowerCase().includes(search.toLowerCase())).length&&<button className="secondary" onClick={()=>setLimit(limit+12)}>Discover more pieces</button>}</div>
   </section>
   <section className="stylist-invite"><StylistWelcome/><div><p className="eyebrow">YOUR BRAND. YOUR AI STYLIST.</p><h2>A familiar face.<br/><em>A personal touch.</em></h2><p>Meet Yuna, your AI Twin shopping stylist. Find a piece you love, discover thoughtful recommendations, and put your look together as you shop.</p><p>Every brand curates how its stylist looks, feels, and sounds—from appearance and personality to voice and styling advice—to connect with its audience.</p><button className="text-link" onClick={()=>open('stylist')}>Shop with your AI stylist ↗</button><span className="concept">BRAND-CURATED STYLIST · CONCEPT PREVIEW</span></div></section><section className="editorial-note"><p className="eyebrow">ALWAYS ON</p><h2>Less imagining.<br/><em>More knowing.</em></h2><p>{active?'Your perspective is already part of the experience. Personal views, fit guidance, and the brand’s edit follow you as you browse.':'A photo. A few details, added to your SPREEAI account once. Then personal views, fit guidance, and recommendations appear as you shop.'}</p>{active?<span className="connected-label">✧ Always On is enabled</span>:<button className="text-link" onClick={()=>open('signin')}>Turn on your personal experience ↗</button>}</section>
   {recommendationRail(mode==='personal'?'Recommended for you. Already on you.':mode==='twin'?`The brand’s edit. Seen on ${who}.`:'The creative studio’s edit.')}
  </>}
  {product&&<>
   <div className="breadcrumb"><Link to="/">The collection</Link><span>/</span><span>{product.category}</span></div>
   <section className="pdp"><Gallery key={`${product.id}-${person}-${mode}-${mediaOrder}`} product={product} person={person} active={active} who={who} initialId={initialMedia} personalFirst={mediaOrder==='personal'} onUnlock={i=>{setInitialMedia(i);open('unlock')}}/>
   <div className="product-details"><p className="eyebrow">SPREEAI / THE TRANSITIONAL EDIT</p><h1>{product.name}</h1><p className="price">{money(product.price)}</p><p className="description">{product.description}</p><p className="color">{product.color!=='As shown'&&<span style={{background:product.color==='Ivory'?'#ddd7c5':product.color==='Silver'?'#aaa':product.color==='Noir'?'#202020':'#582432'}}/>}{product.color}</p>
    <div className="fit-inline">{badge}<div><strong>{active?`${mode==='personal'?'Your size':'Twin size'}: ${recommended}`:'A more personal fit'}</strong><button onClick={()=>open(active?'why':'signin')}>{active?'Why this size?':'Set up your profile ↗'}</button></div><small>{active?`Illustrative recommendation · ${mode==='personal'?profile.fit:'Regular'} fit`:'Your photo and a few details, saved to your account.'}</small></div>
    <div className="size-heading"><span>{size?`Selected size: ${size}`:'Select a size'}</span><button onClick={()=>open('why')}>Size guide</button></div><div className="sizes">{product.sizes.map(x=><button aria-pressed={size===x} className={active&&x===recommended?'recommended':''} key={x} onClick={()=>{setSize(x);setError('')}}>{x}{active&&x===recommended&&<small>Suggested</small>}</button>)}</div>
    {error&&<p role="alert" className="error">{error}</p>}<button className="primary full" onClick={()=>{if(!size){setError('Choose a size to add this piece to your bag.');return}setBag([...bag,{id:product.id,size}]);setToast('Added to your local shopping bag')}}>Add to bag</button><button className="secondary full" onClick={()=>{if(!active){open('unlock');return}setCompare([product.id,products.find(p=>p.id!==product.id&&p.category===product.category)?.id||products.find(p=>p.id!==product.id)!.id]);open('compare')}}>Compare this piece</button>
    <div className="journey-inline"><SavePiece id={product.id} isSample={isJourneySample} onStart={()=>{setPendingJourneyPiece(product.id);open('journey')}}/><p>Keep your favorites together, then review them with your associate.</p><button className="text-link" onClick={()=>open('journey')}>Review my edit ↗</button></div>
    <button className="text-link full" onClick={()=>document.getElementById('product-outfit-builder')?.scrollIntoView({behavior:'smooth',block:'start'})}>Build an outfit with this piece ↓</button><button className="text-link full" onClick={()=>open('stylist')}>Ask your AI stylist ↗</button>{product.id==='knit-polo'&&<button className="text-link full" onClick={()=>open(active?'colors':'unlock')}>Compare Bordeaux & Ivory ↗</button>}<p className="shipping">Complimentary delivery & returns<br/><small>Demonstration store · No checkout or charges</small></p>
    <details><summary>Details & composition <span>+</span></summary><p>{product.details}</p><p>{product.material}</p></details><details><summary>Delivery & returns <span>+</span></summary><p>For the finished retailer experience, delivery dates and return eligibility would come from the partner’s commerce system.</p></details>
   </div></section><section id="product-outfit-builder" className="product-outfit-section" aria-label={`Outfit builder for ${product.name}`}><Stylist key={`outfit-${product.id}-${person}`} currentProduct={product} person={person} voice={voice} builderOnly embedded onBag={items=>{setBag([...bag,...items]);setToast('Your outfit was added to your local bag')}}/></section>{recommendationRail('Continue your story.')}
  </>}
  {account&&<section className="account"><p className="eyebrow">MY SPREEAI</p><h1>{mode==='personal'?`Welcome, ${profile.name}.`:'Make yourself at home.'}</h1><p>One account. A wardrobe that knows your perspective.</p><div className="account-layout"><aside><p className="selected">Your profile</p><button onClick={()=>open('journey')}>My edit & appointment preview ↗</button><p>Orders <small>Demo</small></p><button onClick={()=>open('saved')}>Saved looks ↗</button>{mode==='personal'&&<button onClick={()=>switchMode('out')}>Sign out</button>}</aside><div className="account-profile">{badge}<h2>Your fit & visualization profile</h2><p>{mode==='personal'?'Connected to your SPREEAI account. Ready wherever you browse.':'Enable SPREEAI inside your SPREEAI account. Your photo and details stay together, so you only set up once.'}</p>{mode==='personal'?<><div className="profile-summary"><img src={profile.photo==='sample'||!profile.photo?asset(person,0):profile.photo} alt="Profile photo"/><div><strong>{profile.name}</strong><p>{Math.round(profile.height)} cm · {Math.round(profile.weight)} kg<br/>{profile.fit} fit preference</p><span className="concept">ALWAYS ON · LOCAL DEMO</span></div></div><button className="primary" onClick={()=>open('profile')}>Edit your profile</button><button className="text-link" onClick={()=>{setProfile(sampleProfile);localStorage.removeItem('ao-profile');setMode('out');setPhoto('');setToast('Local profile removed')}}>Remove local profile</button></>:<button className="primary" onClick={()=>open('signin')}>Sign in or create an account</button>}<div className="account-benefits"><div><strong>01 / Set up once</strong><p>A photo and your fit details.</p></div><div><strong>02 / See it everywhere</strong><p>Personal views appear as you browse.</p></div><div><strong>03 / Keep your perspective</strong><p>Return to a familiar experience.</p></div></div>{previewNotice}</div></div></section>}
  </main>
  <footer><div className="footer-logo"><img src="/spreeai-logo.svg" alt="SPREEAI"/></div><div><span>An interactive demo storefront.</span><p>Always On, powered by SPREEAI.</p></div><button onClick={()=>{setStep(0);open('guide')}}>Meet your guide ↗</button><p className="fine">Local partner showcase · SPREEAI catalog & generated previews · Concept features labeled</p></footer>
  {compare.length>0&&!panel&&<div className="compare-tray"><span>Your edit · {compare.length} of 2</span><button onClick={compareOpen}>Compare pieces ↗</button><button aria-label="Clear comparison" onClick={()=>setCompare([])}>×</button></div>}
  <div className="demo-switch"><TutorialToggle/><span>DEMO STATE</span><select aria-label="Demo state" value={mode} onChange={e=>switchMode(e.target.value as Mode)}><option value="out">Signed Out</option><option value="twin">AI Twin</option><option value="personal">Signed In Personalized</option></select><details className="brand-settings"><summary>Brand settings</summary><label>Stylist persona<select aria-label="Brand stylist persona" value={voice} onChange={e=>{const v=e.target.value as 'director'|'advisor';setVoice(v);localStorage.setItem('ao-voice',JSON.stringify(v))}}><option value="director">Creative director</option><option value="advisor">Personal shopping advisor</option></select></label><label>Product imagery order<select aria-label="Brand product imagery order" value={mediaOrder} onChange={e=>{const v=e.target.value as 'model'|'personal';setMediaOrder(v);setInitialMedia('');localStorage.setItem('ao-media-order',JSON.stringify(v))}}><option value="model">Product & model first (default)</option><option value="personal">Shopper first when enabled</option></select></label><small>Demo configuration · Brand controls voice, curation, and imagery order.</small></details><button className="developer-switch" role="switch" aria-checked={panel==='developer'} aria-label="Developer mode" onClick={()=>open('developer')}><span className="developer-toggle" aria-hidden="true"/>Developer mode <small>Coming soon</small></button><span className="demo-dot"/></div>
  {toast&&<div className="toast" role="status">✓ {toast}</div>}
  <Dialog.Root open={!!panel} onOpenChange={v=>{if(!v)close()}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className={`modal ${panel==='profile'?'drawer':''} ${['journey','twins','compare','stylist','saved','colors'].includes(panel||'')?'wide':''} ${panel==='guide'?'guide-modal':''} ${panel==='checkout'?'checkout-modal':''}`} aria-describedby="modal-description"><Dialog.Close className="close" aria-label="Close dialog">×</Dialog.Close>
   <Dialog.Title className="sr-only">{panel==='journey'?'Your connected edit':panel==='checkout'?'Your Always On checkout moment':panel==='developer'?'Developer sandbox':panel==='guide'?'Your Always On guide':panel==='unlock'?'Unlock your perspective':panel==='twins'?'Choose your AI Twin':panel==='profile'?'Your personal profile':panel==='signin'?'Sign in to SPREEAI':panel==='why'?'Your size explained':panel==='bag'?'Your shopping bag':panel==='stylist'?'Your AI stylist':panel==='saved'?'Your saved looks':panel==='colors'?'Compare colors':'Compare your edit'}</Dialog.Title><Dialog.Description id="modal-description" className="sr-only">{panel==='guide'?'A guided introduction to the local Always On experience.':'Explore the local SPREEAI partner demo.'}</Dialog.Description>
   {!['journey','stylist','saved'].includes(panel||'')&&<FeatureNote key={`tutorial-${panel}`} panel={panel}/>}
   {panel==='journey'&&<Journey isSample={isJourneySample} onStart={startJourney} onClose={close}/>}
   {panel==='developer'&&<div className="modal-body developer-placeholder"><p className="eyebrow">SPREEAI / DEVELOPER MODE</p><span className="concept">COMING SOON</span><h2>Your sandbox.<br/>Room to experiment.</h2><p>A dedicated space for your development team to explore SPREEAI features and experiment with storefront experiences.</p><div className="developer-preview"><span aria-hidden="true">〈 / 〉</span><strong>Sandbox under construction</strong><p>Developer tools and configuration controls will live here. This is a preview placeholder; the sandbox is not available yet.</p></div><button className="primary full" onClick={close}>Return to the demo →</button></div>}
   {panel==='guide'&&<Guide step={step} setStep={setStep} onClose={close} onAccount={()=>{open(mode==='personal'?'profile':'signin')}} onTwin={()=>{open('twins')}}/>}
   {panel==='unlock'&&<div className="modal-body"><p className="eyebrow">YOUR PERSPECTIVE, ALWAYS ON</p><h2>See it your way.</h2><p>Two ways to bring this piece to life.<br/>Choose what feels right for you.</p><button className="unlock-option" onClick={()=>{setChosenTwin(person);open('twins')}}><span>01</span><div><h3>Use an AI Twin</h3><p>Choose a preset person. See it instantly.</p><small>No account or photo needed</small></div><span>↗</span></button><button className="unlock-option" onClick={()=>open('signin')}><span>02</span><div><h3>Sign in to see yourself</h3><p>Your photo, your fit, your perspective.</p><small>Saved in your SPREEAI account</small></div><span>↗</span></button>{badge}</div>}
   {panel==='twins'&&<div className="modal-body"><p className="eyebrow">NO ACCOUNT NEEDED</p><h2>Find your perspective.</h2><p>Choose an AI Twin to explore the collection.<br/>Preset measurements describe the twin, not your personal fit.</p><div className="twin-grid">{twins.map((t,i)=><button key={t.name} className={chosenTwin===i?'selected':''} aria-pressed={chosenTwin===i} onClick={()=>setChosenTwin(i)}>{photoView(0,i)}<strong>{t.name}{chosenTwin===i?' ✓':''}</strong><small>{t.height} cm · {t.weight} kg</small><small>Sample size {t.size}</small></button>)}</div><div className="modal-actions">{badge}<button className="primary" onClick={()=>{setPerson(chosenTwin);setMode('twin');close();setToast(`Your collection is now shown on ${twins[chosenTwin].name}`)}}>Continue with {twins[chosenTwin].name} →</button></div></div>}
   {panel==='signin'&&<div className="modal-body"><p className="eyebrow">MY SPREEAI</p><h2>A familiar place.<br/>A personal experience.</h2><p>Connect your SPREEAI profile to the account you already use to shop.</p><div className="signin-demo"><strong>Partner account simulation</strong><p>Continue as Alex to explore sign-in, or create a new local profile. No password required.</p></div><button className="primary full" onClick={()=>{setProfile(sampleProfile);setPhoto('sample');setMeasure({height:sampleProfile.height,weight:sampleProfile.weight});setUnit('metric');setPanel('profile')}}>Continue as Alex</button><button className="secondary full" onClick={()=>{setProfile({...sampleProfile,name:'',photo:''});setPhoto('');setMeasure({height:sampleProfile.height,weight:sampleProfile.weight});setUnit('metric');setPanel('profile')}}>Create a local account</button><button className="text-link" onClick={()=>open('twins')}>Continue without an account</button>{badge}</div>}
   {panel==='profile'&&<form className="modal-body profile-form" onSubmit={finishProfile}><p className="eyebrow">MY SPREEAI / POWERED BY SPREEAI</p><h2>Your perspective,<br/>saved.</h2><p>Your SPREEAI account stays at the center. These additional details switch on your personal shopping experience.</p><label>Age group<select value={age} onChange={e=>{setAge(e.target.value);setPhoto('')}}><option value="adult">18 or older</option><option value="teen">13–17</option><option value="child">Under 13</option></select></label>{age==='child'?<p className="error">SPREEAI is not available to children under 13.</p>:age==='teen'?<><p>Personal uploads are unavailable for ages 13–17. This prototype contains adult sample twins only; age-appropriate twins are not included yet.</p><button type="button" className="secondary full" onClick={close}>Return to collection</button></>:<>
    <div className="photo-input">{photo&&<img src={photo==='sample'?asset(1,0):photo} alt="Your selected profile photo"/>}<div><strong>Your photo</strong><p>A clear, full-body photo in fitted clothing.</p><label className="text-link">Upload photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setError('Choose a JPG, PNG or WebP smaller than 8 MB.');return}const reader=new FileReader();reader.onload=()=>{setPhoto(String(reader.result));setError('')};reader.readAsDataURL(file)}}/></label><button type="button" className="text-link" onClick={()=>setPhoto('sample')}>Use sample photo</button></div></div>
    <p className="fine">Uploads stay in this tab and are not sent anywhere. Sample visuals represent personalization; your photo is not transformed.</p>
    <label>First name<input name="name" defaultValue={profile.name} required maxLength={40}/></label><div className="unit-toggle"><button type="button" className={unit==='metric'?'selected':''} onClick={()=>setUnit('metric')}>Metric</button><button type="button" className={unit==='imperial'?'selected':''} onClick={()=>setUnit('imperial')}>Imperial</button></div><div className="form-row" key={unit}><label>Height ({unit==='metric'?'cm':'in'})<input name="height" type="number" required min={unit==='metric'?100:39} max={unit==='metric'?230:91} step="0.1" value={Math.round((unit==='metric'?measure.height:measure.height/2.54)*10)/10} onChange={e=>setMeasure({...measure,height:Number(e.target.value)*(unit==='imperial'?2.54:1)})}/></label><label>Weight ({unit==='metric'?'kg':'lb'})<input name="weight" type="number" required min={unit==='metric'?30:66} max={unit==='metric'?250:551} step="0.1" value={Math.round((unit==='metric'?measure.weight:measure.weight/0.453592)*10)/10} onChange={e=>setMeasure({...measure,weight:Number(e.target.value)*(unit==='imperial'?.453592:1)})}/></label></div><label>Sizing profile<select name="gender" defaultValue={profile.gender}><option>Male</option><option>Female</option></select><small>Current model input; does not limit which collection you browse.</small></label><label>Preferred fit<select name="fit" defaultValue={profile.fit}><option>Close</option><option>Regular</option><option>Relaxed</option></select></label><label className="checkbox"><input type="checkbox" name="consent" required defaultChecked={mode==='personal'}/><span>Enable visualization and fit previews with my local profile.</span></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" type="submit">Save profile & turn Always On →</button><p className="fine">Your details are stored in this browser for this local demo. Remove them from My Account at any time.</p></>}</form>}
   {panel==='why'&&<div className="modal-body"><p className="eyebrow">A LITTLE MORE CERTAINTY</p><h2>{active?`${mode==='personal'?'Your':'Twin'} size: ${recommended}`:'Find your fit.'}</h2><p>{active?`${mode==='personal'?profile.fit:'Regular'} fit · Illustrative recommendation`:'Connect your profile to preview personalized recommendations.'}</p><div className="sizing-roadmap"><div><strong>Find your size</strong><p>A recommendation based on your profile and garment information.</p></div><div><span className="concept">COMING SOON</span><strong>See how you like it to fit</strong><p>Preview relaxed, regular, or close-fitting clothing on you, alongside your size recommendation.</p></div></div><div className="fit-explanation"><div><span>Profile</span><strong>{mode==='personal'?`${Math.round(profile.height)} cm · ${Math.round(profile.weight)} kg`:`${twins[person].height} cm · ${twins[person].weight} kg`}</strong></div><div><span>Preference</span><strong>{mode==='personal'?profile.fit:'Regular'}</strong></div><div><span>Confidence</span><strong>Not measured in this prototype</strong></div></div><p>The finished experience would combine your size profile with validated garment data. Visualization alone does not establish fit accuracy.</p><details><summary>Fit notes · Concept preview</summary><p>{product?.category==='Bottoms'?'Example only: ease through the waist and seat, with the hem falling at the ankle.':product?.category==='Shoes'?'Example only: balanced room across the forefoot and a secure heel.':product?.category==='Accessories'?'Accessory fit depends on the item’s dimensions; no personal measurement is inferred here.':'Example only: regular shoulder line, room through the torso, and sleeves finishing at the wrist.'} Future fit notes would require validated garment and body data; these notes are not calculated from your profile.</p></details>{product?.category!=='Accessories'&&product?.category!=='Shoes'&&product?.category!=='Bottoms'&&<table><caption>Illustrative SPREEAI size chart</caption><thead><tr><th>Size</th><th>Chest (cm)</th></tr></thead><tbody>{[['XS','84–88'],['S','89–94'],['M','95–100'],['L','101–108'],['XL','109–116'],['XXL','117–124']].map(x=><tr key={x[0]}><td>{x[0]}</td><td>{x[1]}</td></tr>)}</tbody></table>}{(product?.category==='Accessories'||product?.category==='Shoes'||product?.category==='Bottoms')&&<p className="fine">Available demo sizes: {product.sizes.join(', ')}. Verify the retailer’s category-specific size chart before ordering; these are sample values.</p>}<button className="secondary full" onClick={()=>open(active?'profile':'signin')}>{active?'Edit profile':'Set up profile'}</button>{previewNotice}</div>}
   {panel==='compare'&&<div className="modal-body"><p className="eyebrow">YOUR EDIT / SIDE BY SIDE</p><h2>Two pieces. One perspective.</h2><p>{mode==='personal'?'On you · sample profile':`On ${who} · ${twins[person].height} cm · ${twins[person].weight} kg`}</p><div className="comparison">{products.filter(p=>compare.includes(p.id)).map(p=><div key={p.id}><img src={displayImage(p,person,active)} alt={`${p.name} · ${p.preview?who:'product view'}`}/><p className="fine">{p.preview?'Personal sample':'Product view · personal preview not prepared'}</p><h3>{p.name}</h3><select aria-label={`Replace ${p.name} in comparison`} value={p.id} onChange={e=>setCompare(compare.map(id=>id===p.id?e.target.value:id))}>{products.filter(q=>q.id===p.id||!compare.includes(q.id)).map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select><p>{money(p.price)} · {p.color}</p><button className="text-link" onClick={()=>{close();nav(`/product/${p.id}`)}}>View piece ↗</button></div>)}</div><div className="modal-actions">{badge}<button className="text-link" onClick={()=>open(mode==='twin'?'twins':'profile')}>Change perspective</button></div>{previewNotice}</div>}
   {panel==='checkout'&&<CheckoutCelebration itemCount={bag.length} onBack={()=>open('bag')} onExplore={()=>{close();nav('/')}}/>}
   {panel==='bag'&&<div className="modal-body"><p className="eyebrow">MY SPREEAI</p><h2>Your shopping bag.</h2>{bag.length?bag.map((item,i)=>{const p=products.find(p=>p.id===item.id)||wardrobe.find(p=>p.id===item.id)!;return <div className="bag-item" key={i}><img src={p.image} alt={p.name}/><div><strong>{p.name}</strong><p>Size {item.size} · {money(p.price)}</p><button className="text-link" onClick={()=>setBag(bag.filter((_,j)=>j!==i))}>Remove</button></div></div>}):<p>Your next favorite piece is waiting in the collection.</p>}<p>Local demo only. No payment or order will be placed.</p>{bag.length>0&&<button className="primary full" onClick={()=>open('checkout')}>Continue to checkout →</button>}<button className="secondary full" onClick={()=>{close();nav('/')}}>Continue exploring</button></div>}
   {(panel==='stylist'||panel==='saved')&&<Stylist key={panel} currentProduct={product} voice={voice} person={person} savedOnly={panel==='saved'} onBag={items=>setBag([...bag,...items])}/>}
   {panel==='colors'&&<div className="modal-body"><p className="eyebrow">ONE PIECE / TWO PERSPECTIVES</p><h2>Find your color.</h2><p>The merino polo, on {mode==='personal'?'your sample profile':who}.</p><div className="comparison"><div>{photoView(2)}<h3>Bordeaux</h3></div><div><img src={`/always-on-assets/style-0-${person}.webp`} alt={`${who} wearing an ivory polo`}/><h3>Ivory</h3></div></div><p className="fine">Sample color comparison. Ivory is an editorial preview and is not a purchasable variant in this local catalog.</p>{badge}</div>}
  </Dialog.Content></Dialog.Portal></Dialog.Root>
 </>;
}
