import {useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import LiveTryOn from './LiveTryOn';
import type {Product} from './data';
export default function Gallery({product}:{product:Product;person:number;active:boolean;who:string;onUnlock:(id:string)=>void;initialId?:string;personalFirst?:boolean;pending?:boolean}){
 const images=[...new Set([product.image,product.model,...(product.source||[])])];
 const [index,setIndex]=useState(0),[live,setLive]=useState(false),[zoom,setZoom]=useState(false),[scale,setScale]=useState(1);
 return <div className="native-gallery" aria-label="Product gallery"><div className="gallery-tabs"><button aria-pressed={!live&&index===0} onClick={()=>{setLive(false);setIndex(0)}}>The piece</button>{images.length>1&&<button aria-pressed={!live&&index===1} onClick={()=>{setLive(false);setIndex(1)}}>On the model</button>}<button aria-pressed={live} onClick={()=>setLive(true)}>Try on you ↗</button><span className="gallery-identity"><i/> Live SPREEAI collection</span></div>
 {live?<LiveTryOn embedded product={product} onClose={()=>setLive(false)}/>:<div className="gallery-stage"><button className="gallery-image" aria-label="Zoom product image" onClick={()=>{setScale(1);setZoom(true)}}><img src={images[index]} alt={`${product.name} · ${index===0?'product':'model view'}`}/><span>＋</span></button>{images.length>1&&<><button className="gallery-prev" aria-label="Previous product view" onClick={()=>setIndex((index-1+images.length)%images.length)}>‹</button><button className="gallery-next" aria-label="Next product view" onClick={()=>setIndex((index+1)%images.length)}>›</button><div className="gallery-thumbs">{images.map((src,i)=><button key={src} aria-label={`View ${i+1}`} aria-pressed={index===i} onClick={()=>setIndex(i)}><img src={src} alt=""/></button>)}</div></>}</div>}
 <div className="gallery-caption"><span>{live?'Your live try-on':index===0?'The piece':'On the model'}</span><span>Official SPREEAI demo imagery{!live&&` · ${index+1} / ${images.length}`}</span></div>
 <Dialog.Root open={zoom} onOpenChange={setZoom}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="native-zoom" aria-describedby="zoom-description"><Dialog.Title className="sr-only">{product.name} detail</Dialog.Title><Dialog.Description id="zoom-description" className="sr-only">Use zoom controls to inspect the product.</Dialog.Description><div className="zoom-toolbar"><span>{product.name}</span><button aria-label="Zoom out" onClick={()=>setScale(Math.max(1,scale-.5))}>−</button><span>{scale*100}%</span><button aria-label="Zoom in" onClick={()=>setScale(Math.min(3,scale+.5))}>＋</button><Dialog.Close aria-label="Close detail viewer">×</Dialog.Close></div><div className="native-zoom-image"><img src={images[index]} alt={product.name} style={{transform:`scale(${scale})`}}/></div></Dialog.Content></Dialog.Portal></Dialog.Root></div>
}
