import {useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import PersonalViews from './PersonalViews';
import {useConnectedProfile} from './connection';
import {usePersonalImage} from './personalization';
import type {Product} from './data';
export default function Gallery({product}:{product:Product;onSize?:(size:string)=>void;person:number;active:boolean;who:string;onUnlock:(id:string)=>void;initialId?:string;personalFirst?:boolean;pending?:boolean}){
 const images=[...new Set([product.image,product.model,...(product.source||[])])];const profile=useConnectedProfile();const personal=usePersonalImage([product]);
 const slots=[...images.slice(0,2).map((src,i)=>({src,label:i===0?'The piece':'On the model',view:''})),...['front','back','video'].map((view,i)=>({src:'',view,label:['On you','Back view','In motion'][i]})),...images.slice(2).map((src,i)=>({src,label:'Detail '+(i+1),view:''}))];
 const [index,setIndex]=useState(0),[zoom,setZoom]=useState(false);const slot=slots[index];
 return <div className="native-gallery" aria-label="Product gallery"><div className="gallery-tabs">{slots.map((s,i)=><button key={i} aria-pressed={index===i} onClick={()=>setIndex(i)}>{s.label}{['back','video'].includes(s.view)?' · Coming soon':''}</button>)}</div><div className="gallery-slide-shell" onTouchStart={e=>{e.currentTarget.dataset.start=String(e.touches[0].clientX)}} onTouchEnd={e=>{const diff=Number(e.currentTarget.dataset.start)-e.changedTouches[0].clientX;if(Math.abs(diff)>80)setIndex(i=>Math.max(0,Math.min(slots.length-1,i+(diff>0?1:-1))))}}>
 {slot.view?<PersonalViews key={slot.view} product={product} initial={slot.view}/>:<div className="gallery-stage"><button className="gallery-image" aria-label="Zoom product image" onClick={()=>setZoom(true)}><img src={slot.src} alt={`${product.name} · ${slot.label}`}/><span>＋</span></button></div>}
 <div className="gallery-pagination"><button disabled={index===0} aria-label="Previous product view" onClick={()=>setIndex(index-1)}>←</button><span>{String(index+1).padStart(2,'0')} / {String(slots.length).padStart(2,'0')}</span><button disabled={index===slots.length-1} aria-label="Next product view" onClick={()=>setIndex(index+1)}>→</button></div></div><div className="personal-thumbnails">{slots.map((s,i)=><button key={i} aria-pressed={index===i} onClick={()=>setIndex(i)}>{s.src?<img src={s.src} alt=""/>:s.view==='front'&&profile.identity?<img className={personal.url?'':'awaiting-view'} src={personal.url||profile.identity.url} alt={personal.url?'Your personal garment preview':'Personal preview loading'}/>:<span>{s.view==='front'?'＋':'Soon'}</span>}<small>{s.label}</small></button>)}</div>
 <Dialog.Root open={zoom} onOpenChange={setZoom}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="native-zoom" aria-describedby="zoom-description"><Dialog.Title className="sr-only">{product.name}</Dialog.Title><Dialog.Description id="zoom-description" className="sr-only">Original garment photography.</Dialog.Description><div className="zoom-toolbar"><span>{product.name}</span><Dialog.Close aria-label="Close detail viewer">×</Dialog.Close></div><div className="native-zoom-image"><img src={slot.src} alt={product.name}/></div></Dialog.Content></Dialog.Portal></Dialog.Root></div>
}
