import AutoVideo from './AutoVideo';
import {useState,useEffect,useRef} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {personalImage,brandPerson} from './data';
import FeatureNote from './FeatureNote';
import {garmentDirection,directedPoses} from './direction';
import type {Product} from './data';
type Media={id:string;label:string;personal:boolean;src:string;kind:'image'|'video'};
const poses=['front','pose1','pose2','back'];
export default function Gallery({product,person,active,who,onUnlock,initialId='',personalFirst=false}:{product:Product;person:number;active:boolean;who:string;onUnlock:(id:string)=>void;initialId?:string;personalFirst?:boolean}){
 const direction=garmentDirection(product);
 const movie=person===1?`/always-on-assets/editorial-${product.id}-alex.mp4`:product.preview==='imported'?`/always-on-assets/${product.id}-${person}.mp4`:product.preview==='core'?`/always-on-assets/turn-${person}-${product.row}.mp4`:`/always-on-assets/look-turn-${person}.mp4`;
 const brand:Media[]=[{id:'piece',label:'The piece',personal:false,src:product.image,kind:'image'},{id:'model',label:'On the model',personal:false,src:personalImage(product,brandPerson(product),'front')||product.model,kind:'image'},{id:'detail',label:'Product detail',personal:false,src:product.image,kind:'image'}];
 const personal:Media[]=[...poses.map(pose=>({id:`personal-${pose}`,label:`On you · ${{front:'Front-facing',pose1:person===1?`Brand pose · ${directedPoses(product)?.labels[0]||'Editorial stance'}`:'Brand pose 1',pose2:person===1?`Brand pose · ${directedPoses(product)?.labels[1]||'Editorial gesture'}`:'Brand pose 2',back:'Back · simulated'}[pose]}`,personal:true,src:personalImage(product,person,pose)||product.image,kind:'image' as const})),{id:'motion',label:'Your motion',personal:true,src:movie,kind:'video'}];
 const slots=personalFirst&&active?[...personal,...brand]:[...brand,...personal];
 const [selected,setSelected]=useState(initialId||slots[0].id),[zoom,setZoom]=useState(false),[scale,setScale]=useState(1),[position,setPosition]=useState({x:50,y:50}),[loaded,setLoaded]=useState<string[]>([]);
 const index=Math.max(0,slots.findIndex(s=>s.id===selected)),current=slots[index];
 const rail=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(initialId)rail.current?.querySelector(`[data-media="${initialId}"]`)?.scrollIntoView({block:'center',behavior:'smooth'})},[initialId]);
 function inspect(item:Media){setSelected(item.id);if(item.personal&&!active){onUnlock(item.id);return}setScale(item.kind==='video'?1:1.5);setPosition({x:50,y:50});setZoom(true)}
 return <div className="gallery-column" ref={rail}>
 <div className="scroll-gallery" aria-label="Product gallery">{slots.map((item,i)=><div key={item.id} data-media={item.id} className={`scroll-frame ${item.personal?'personal-frame':''} ${item.kind==='video'?'motion-frame':''}`}>
 {item.personal&&(i===0||!slots[i-1].personal)&&<div className="personal-gallery-intro"><span className="powered">Powered by SPREEAI</span><h2>{active?`Now, on ${who}.`:'Your perspective, next.'}</h2><p>{active?'Front-facing first. Two poses directed by the brand. A simulated back view to complete the perspective.':'Sign in once or choose an AI Twin to unlock your views.'}</p><span className="concept">PERSONAL VIEWS · SIMULATED DEMO</span><FeatureNote panel="poses" inline/><details className="partner-direction"><summary>Partner-directed poses · {product.name}</summary><h3>{direction.title}</h3><p>{direction.context}</p><ol>{direction.poses.map(pose=><li key={pose}>{pose}</li>)}</ol><p className="fine">Your brand directs the two middle poses for each garment—stance, gestures, framing, and mood. Alex’s editorial examples show different creative directions across the collection. These are prepared demo images; changing a brief does not run live generation. The back view is always simulated, not a verified reconstruction of unseen details.</p></details></div>}
 {item.kind==='video'&&<><FeatureNote panel="motion" inline/><div className="motion-direction"><p className="eyebrow">PARTNER-DIRECTED MOTION</p><h3>{direction.title}</h3><p>{direction.action}</p><small>Example direction for this garment · The clip below is a pose storyboard, not a generated performance of this action.</small></div></>}<div className="scroll-frame-media">{item.personal&&!active?<button className="locked-scroll" onClick={()=>onUnlock(item.id)} aria-label={`Unlock ${item.label}`}><img loading="lazy" className="locked-image" src={product.image} alt=""/><span><strong>⌑ {item.label}</strong><small>Use an AI Twin or sign in to see yourself ↗</small></span></button>:item.kind==='video'?<><AutoVideo src={item.src} poster={personalImage(product,person)||product.model} controls loop playsInline preload="metadata" aria-label="Personalized motion storyboard"/><button className="video-expand" onClick={()=>inspect(item)}>Full screen ↗</button></>:<button className={`image-zoom ${loaded.includes(item.src)?'':'loading'} ${item.id==='detail'?'detail-crop':''}`} onClick={()=>inspect(item)} aria-label={`Zoom ${item.label}`}><img loading={i<2?'eager':'lazy'} src={item.src} onLoad={()=>setLoaded(current=>current.includes(item.src)?current:[...current,item.src])} alt={`${product.name} · ${item.personal?who:item.id==='model'?'brand model':'product'} · ${item.label}`}/><span>+</span></button>}</div>
 {item.id==='personal-back'&&<p className="back-disclosure"><strong>Simulated back view.</strong> Unseen garment details cannot be predicted reliably. This illustration is not a verified reconstruction.</p>}<div className="frame-caption"><span>{item.label}{item.personal&&active?` · ${who}`:''}</span><span>{String(i+1).padStart(2,'0')} / {slots.length}</span></div>
 </div>)}</div><p className="fine">{personalFirst&&active?'Personal views lead, as selected in brand settings.':'Garment photography, the collection model, and a close-up detail; then SPREEAI front-facing, two brand-directed poses, simulated back, and video views.'} Poses and motion are prepared simulations.</p>
 <Dialog.Root open={zoom} onOpenChange={setZoom}><Dialog.Portal><Dialog.Overlay className="overlay zoom-overlay"/><Dialog.Content className="zoom-dialog" aria-describedby="zoom-help"><Dialog.Title className="sr-only">{product.name} detail viewer</Dialog.Title><Dialog.Description id="zoom-help" className="sr-only">Use zoom controls and drag the image to inspect details.</Dialog.Description><FeatureNote key={current.personal?(current.kind==='video'?'motion':'poses'):'zoom'} panel={current.personal?(current.kind==='video'?'motion':'poses'):'zoom'}/><div className="zoom-toolbar"><span>{product.name}</span>{current.kind!=='video'&&<><button aria-label="Zoom out" onClick={()=>setScale(Math.max(1,scale-.5))}>−</button><span>{Math.round(scale*100)}%</span><button aria-label="Zoom in" onClick={()=>setScale(Math.min(4,scale+.5))}>+</button><button onClick={()=>{setScale(1);setPosition({x:50,y:50})}}>Reset</button></>}<Dialog.Close aria-label="Close detail viewer">×</Dialog.Close></div>{current.kind==='video'?<AutoVideo src={current.src} controls playsInline/>:<div className="zoom-canvas" onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(e.buttons||e.pressure){setPosition(p=>({x:Math.max(0,Math.min(100,p.x-e.movementX/3)),y:Math.max(0,Math.min(100,p.y-e.movementY/3))}))}}}><img src={current.src} alt={`${product.name}, enlarged detail`} style={{transform:`scale(${scale})`,transformOrigin:`${position.x}% ${position.y}%`}} draggable={false}/></div>}<p className="zoom-hint">{current.kind==='video'?'Motion storyboard · local concept':'Drag to explore · Zoom up to 400% · Escape to close'}</p></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>
}
