import {useEffect,useRef,useState} from 'react';
import {sdkURL,isSdkClose} from './sdk';
export default function LiveTryOn({signedIn,onClose,onSignIn}:{signedIn:boolean;onClose:()=>void;onSignIn:()=>void}){
 const [started,setStarted]=useState(false),[fit,setFit]=useState(false),[loaded,setLoaded]=useState(false),[slow,setSlow]=useState(false);const frame=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{if(!started)return;const timer=setTimeout(()=>setSlow(true),12000);return()=>clearTimeout(timer)},[started]);
 useEffect(()=>{function receive(e:MessageEvent){if(isSdkClose(e.origin,e.source,frame.current?.contentWindow,e.data))onClose()}
 window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[onClose]);
 return <div className="modal-body live-tryon"><p className="eyebrow">CONNECTED ENGINEERING DEMO</p><h2>Try it on.</h2><p>Dominican Mixed-Floral Wide Leg Pant · Oscar de la Renta</p>{!started?<><p>This opens SPREEAI’s existing development try-on service with a verified garment. {signedIn?'Photo uploads, if you choose to use them, go directly to SPREEAI’s development service.':'You can use preset AI Twins in the collection without an account. Sign in to the demonstration account to open the connected service.'}</p><label className="checkbox"><input type="checkbox" checked={fit} onChange={e=>setFit(e.target.checked)}/> Intelligent Fit · development preview</label><button className="primary full" onClick={()=>signedIn?setStarted(true):onSignIn()}>{signedIn?'Launch connected try-on':'Sign in to open connected try-on'}</button><p className="fine">The retailer account and this service are not linked. Results remain inside the service; a gallery-result API has not been confirmed.</p></>:<>{!loaded&&<p role="status">Connecting to SPREEAI…</p>}<iframe ref={frame} src={sdkURL(signedIn,fit)} title="Connected SPREEAI virtual try-on" onLoad={()=>setLoaded(true)} sandbox="allow-scripts allow-forms allow-same-origin allow-popups"/><p className="fine">Live development service · separate from prepared storefront previews.</p>{slow&&<p>If the service is unavailable, <a href="https://demo-store.dev.spreeai.com/" target="_blank" rel="noopener">open the engineering demo ↗</a>.</p>}</>}</div>
}
