import {useState,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Link} from 'react-router';
type Piece={id:string;name:string};
export default function LookPreview({images,title,pieces,children,detail,onProduct}:{images:string[];title:string;pieces:Piece[];children:ReactNode;detail?:string;onProduct?:()=>void}){
 const [open,setOpen]=useState(false),[index,setIndex]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false);
 const url=images[index]||images[0],productLink=pieces[0]?new URL(`/spreeai-always-on-demo/online/product/${pieces[0].id}/`,window.location.origin).href:window.location.href;
 async function imageFile(){const r=await fetch(url,{credentials:'omit'});if(!r.ok)throw Error('Image download unavailable');const blob=await r.blob();if(!blob.type.startsWith('image/'))throw Error('Image download unavailable');return new File([blob],`SPREEAI-look-${index+1}.${blob.type==='image/png'?'png':blob.type==='image/webp'?'webp':'jpg'}`,{type:blob.type})}
 async function download(){setBusy(true);setMessage('');try{const file=await imageFile(),objectUrl=URL.createObjectURL(file),link=document.createElement('a');link.href=objectUrl;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),60000);setMessage('Your image is ready in Downloads.')}catch{setMessage('Open the original image below to save it from your browser.')}finally{setBusy(false)}}
 async function share(){setBusy(true);setMessage('');try{if(!navigator.share){setMessage('Use a social link below, or copy the product link. Save the image to include it in your post.');return}const file=await imageFile();if(navigator.canShare?.({files:[file]}))await navigator.share({title:'My SPREEAI look',text:title,files:[file]});else await navigator.share({title,text:title,url:productLink})}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setMessage('Sharing is unavailable here. Save the image or use a product-sharing link below.')}finally{setBusy(false)}}
 return <Dialog.Root open={open} onOpenChange={value=>{setOpen(value);setMessage('');setFailed(false)}}><Dialog.Trigger asChild><button className="look-preview-trigger" aria-label={`Enlarge ${title}`}>{children}<span className="look-expand" aria-hidden="true">View look ＋</span></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay look-lightbox-overlay"/><Dialog.Content className="look-lightbox" aria-describedby="look-viewer-description"><Dialog.Close className="look-close" aria-label="Close enlarged look">×</Dialog.Close><div className="look-lightbox-image">{!failed?<img key={url} src={url} alt={title} onError={()=>setFailed(true)}/>:<p>This preview link is unavailable. Open the product below to view your look again.</p>}{images.length>1&&<div className="look-image-controls">{images.map((_,i)=><button key={i} aria-pressed={index===i} onClick={()=>{setIndex(i);setFailed(false);setMessage('')}}>View {i+1}</button>)}</div>}</div><div className="look-lightbox-details"><p className="eyebrow">YOUR ALWAYS ON GALLERY</p><Dialog.Title>{title}</Dialog.Title><Dialog.Description id="look-viewer-description">{detail||'Your look, up close. Revisit the pieces or keep the image.'}</Dialog.Description><div className="look-download-actions"><button className="primary" disabled={busy||failed||!url} onClick={()=>void download()}>Save image</button><button className="secondary" disabled={busy||failed||!url} onClick={()=>void share()}>Share look</button></div>{message&&<p role="status" className="look-share-status">{message}</p>}<div className="look-products"><h3>The pieces</h3>{pieces.map(p=><Link key={p.id} to={`/product/${p.id}`} onClick={()=>{setOpen(false);onProduct?.()}}>{p.name}<span>View product</span></Link>)}</div><div className="look-social"><p>Share the product</p><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(productLink)}`} target="_blank" rel="noreferrer">Facebook</a><a href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(productLink)}&text=${encodeURIComponent('My Always On find: '+title)}`} target="_blank" rel="noreferrer">X</a><button onClick={()=>void navigator.clipboard.writeText(productLink).then(()=>setMessage('Product link copied.')).catch(()=>setMessage('Copy the product address after opening its page.'))}>Copy link</button></div>{url&&<a className="look-original text-link" href={url} target="_blank" rel="noreferrer">Open original image</a>}<p className="fine">Save the image to post on Instagram or another app. Product links open the garment page.</p></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}
