import {useRef} from 'react';
import {Sparkle,ImageSquare} from '@phosphor-icons/react';
import type {Product} from './data';
import {usePersonalFit} from './personalization';
import {FitSummary} from './FitSelector';
import {sizeLabel,isOneSize} from './fit-scale';
import {previewPlan,sizeFitLabel} from './fit-preview';
export default function SizeDropdown({product,size,onSize}:{product:Product;size:string;onSize:(size:string)=>void}){
 const disclosure=useRef<HTMLDetailsElement>(null),summary=useRef<HTMLElement>(null);
 const fit=usePersonalFit(product),oneSize=isOneSize(product.sizes);
 return <div className="size-studio"><details ref={disclosure} onKeyDown={e=>{if(e.key==='Escape'&&disclosure.current){disclosure.current.open=false;summary.current?.focus()}}}><summary ref={summary}><span><small>SELECTED SIZE</small><strong>{size?sizeLabel(size):'Choose your size'}</strong></span><span className="size-studio-status">{size&&size===fit.recommended?(fit.recommendationSource==='twin'?'Reference size':'Recommended for you'):'See the fit on you'}<i aria-hidden="true">⌄</i></span></summary><div className="size-studio-options visual-fit-options"><div className="visual-fit-intro"><span className="visual-fit-kicker"><Sparkle size={15}/> ALWAYS ON · VISUAL FIT</span><h3>{oneSize?'One piece. Your perspective.':'Don’t just pick a size.\nSee the difference.'}</h3><p>{oneSize?'See this piece on your photo or AI twin. Check the product details for dimensions.':'Start with your recommended fit, then explore another size. Your image above changes to illustrate how the garment could look on you—with more or less room.'}</p></div>{!oneSize&&<div className="fit-story" aria-label="How visual sizing works"><span><span className="fit-story-symbol">S <i>M</i> L</span>Choose a size</span><span className="fit-story-arrow" aria-hidden="true">→</span><span><ImageSquare size={24} weight="thin"/>See it on you</span><span className="fit-story-arrow" aria-hidden="true">→</span><span><span className="fit-story-check">✓</span>Find your fit</span></div>}{fit.recommended&&<div className="fit-recommendation-pill"><span>{fit.recommendationSource==='twin'?'Your starting point':'Recommended for you'}</span><strong>Size {sizeLabel(fit.recommended)}</strong></div>}<div className="shopping-sizes visual-size-grid" role="group" aria-label="Garment sizes">{product.sizes.map(s=>{const recommended=s===fit.recommended,unavailable=!!fit.recommended&&!!previewPlan(product.sizes,s,fit.recommended).reason;const label=fit.recommended?sizeFitLabel(product.sizes,s,fit.recommended,fit.map):'';return <button key={s} className={recommended?'recommended-size':''} aria-pressed={size===s} onClick={()=>{if(disclosure.current)disclosure.current.open=false;summary.current?.focus();onSize(s)}}><span>{sizeLabel(s)}</span>{label&&<small>{recommended&&fit.recommendationSource==='twin'?'Starting size':label}</small>}{unavailable&&<em>Preview soon</em>}{size===s&&<b className="selected-size-tick" aria-hidden="true">✓</b>}</button>})}</div><div className="visual-fit-note"><ImageSquare size={18}/><p>Select a size to reveal your look above.{fit.recommended&&product.sizes.some(s=>!!previewPlan(product.sizes,s,fit.recommended!).reason)&&<small>Sizes marked “Preview soon” can be selected, but their visual previews aren’t available yet.</small>}</p></div></div></details><FitSummary product={product} size={size}/></div>
}
