import StylistWelcome from './StylistWelcome';
import FeatureNote from './FeatureNote';
import {useState} from 'react';
import {money,products} from './data';
import type {Product} from './data';
import {wardrobe as baseWardrobe} from './wardrobe';
const slotFor=(p:Product)=>p.category==='Outerwear'?0:['Shirts','Tops','Knitwear','Dresses'].includes(p.category)?1:p.category==='Bottoms'?2:p.category==='Shoes'?3:4;
type Look={id:number;name:string;items:string[];person:number};
export default function Stylist({person,voice='director',currentProduct,savedOnly=false,builderOnly=false,embedded=false,onBag}:{person:number;currentProduct?:Product;voice?:'director'|'advisor';savedOnly?:boolean;builderOnly?:boolean;embedded?:boolean;onBag:(items:{id:string;size:string}[])=>void}){
 const [wardrobe,setWardrobe]=useState(()=>{if(!currentProduct||baseWardrobe.some(p=>p.id===currentProduct.id))return baseWardrobe;const slot=currentProduct.category==='Outerwear'?0:['Shirts','Tops','Knitwear','Dresses'].includes(currentProduct.category)?1:currentProduct.category==='Bottoms'?2:currentProduct.category==='Shoes'?3:4;return baseWardrobe.map((p,i)=>i===slot?currentProduct:p)});
 const [occasion,setOccasion]=useState('Evening'),[request,setRequest]=useState(''),[answer,setAnswer]=useState('A leather layer, rich burgundy, and clean ivory tailoring. Silver and black accessories keep the finish considered.');
 const [selected,setSelected]=useState(wardrobe.filter(p=>currentProduct?.category!=='Dresses'||p.id!=='trousers').map(p=>p.id)),[sizes,setSizes]=useState<Record<string,string>>({}),[name,setName]=useState('An evening in the city'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[viewSaved,setViewSaved]=useState(savedOnly);
 const [building,setBuilding]=useState(builderOnly);
 const [looks,setLooks]=useState<Look[]>(()=>{try{return JSON.parse(localStorage.getItem('ao-looks')||'[]')}catch{return []}});
 const [lookPerson,setLookPerson]=useState(person);
 const isReference=(ids:string[])=>ids.length===5&&ids.every(id=>baseWardrobe.some(p=>p.id===id));
 function persist(next:Look[]){setLooks(next);localStorage.setItem('ao-looks',JSON.stringify(next))}
 function suggest(value:string){setOccasion(value);setBusy(true);setTimeout(()=>{const relaxed=/weekend|casual|travel|comfortable/i.test(value);setSelected(wardrobe.filter(p=>(!relaxed||p.id!=='leather-jacket')&&(currentProduct?.category!=='Dresses'||p.id!=='trousers')).map(p=>p.id));setName(relaxed?'An unhurried weekend':'An evening in the city');setAnswer(relaxed?'Start with the merino polo and easy ivory tailoring. Loafers bring polish; leave the leather layer behind for a lighter look.':'Balance the biker’s structure with soft merino and ivory tailoring. Black loafers echo the leather; a silver cuff picks up the hardware.');setBusy(false)},650)}
 return <div className={`stylist ${embedded?'embedded-builder':'modal-body'}`}><p className="eyebrow">{voice==='director'?'SPREEAI / THE CREATIVE DIRECTOR’S EDIT':'SPREEAI / PERSONAL SHOPPING'}</p><h2>{viewSaved?'Looks worth keeping.':building?'Build your outfit.':voice==='director'?'From the creative studio.':'Your personal shopping edit.'}</h2>{!embedded&&<div className="style-tabs"><button className={!viewSaved&&!building?'selected':''} onClick={()=>{setViewSaved(false);setBuilding(false)}}>AI stylist</button><button className={viewSaved?'selected':''} onClick={()=>setViewSaved(true)}>Saved looks ({looks.length})</button></div>}
 {(viewSaved||building)&&<FeatureNote key={viewSaved?'saved':'builder'} panel={viewSaved?'saved':'builder'} inline/>}
 {!viewSaved&&!building&&<StylistWelcome/>}
 {viewSaved?<>{looks.length===0?<p>Save an outfit from the outfit builder to make it part of your edit.</p>:looks.map(look=><div className="saved-look" key={look.id}><img src={isReference(look.items)?`/always-on-assets/style-1-${look.person}.webp`:products.find(p=>p.id===look.items[0])?.image} alt="Saved look preview"/><div><h3>{look.name}</h3><p>{look.items.length} pieces · Saved on this device</p><button className="text-link" onClick={()=>{setSelected(look.items);setWardrobe(baseWardrobe.map((fallback,index)=>products.find(p=>look.items.includes(p.id)&&slotFor(p)===index)||fallback));setName(look.name);setLookPerson(look.person);setViewSaved(false);setBuilding(true);setNotice('Saved outfit restored')}}>Revisit & edit ↗</button><button className="text-link" onClick={()=>persist(looks.filter(l=>l.id!==look.id))}>Delete look</button></div></div>)}</>:<>
 {building?<p>Start with a piece you love. Swap layers, clothing, shoes and accessories from the collection, then save your look or choose sizes to shop it.</p>:<><p>{voice==='director'?'Explore SPREEAI through our creative studio’s point of view. Tell us where you’re going; we’ll help you make the collection your own.':'Let’s find pieces for your day. Tell us the occasion and explore a thoughtful selection from SPREEAI.'}</p><span className="concept">BRAND-CURATED AI STYLIST · CONCEPT</span><div className="occasion">{['Evening','Weekend','Travel'].map(o=><button key={o} aria-pressed={occasion===o} onClick={()=>suggest(o)}>{o}</button>)}</div><form className="style-request" onSubmit={e=>{e.preventDefault();if(request.trim())suggest(request)}}><input aria-label="Ask your stylist" placeholder="Something relaxed for a weekend away…" value={request} onChange={e=>setRequest(e.target.value)} maxLength={160}/><button className="primary" disabled={!request.trim()||busy}>Style my edit</button></form><p className="stylist-answer" role="status">{busy?'Considering your edit…':currentProduct?`Start with ${currentProduct.name.toLowerCase()}. ${voice==='director'?'Our studio would keep the accompanying pieces restrained, letting this piece set the direction.':'These complementary pieces keep your outfit easy to wear. Adjust your selection and choose each size below.'}`:answer}</p></>}
 <div className="outfit-layout"><div>{isReference(selected)?<img className="outfit-preview" src={`/always-on-assets/style-1-${lookPerson}.webp`} alt="Five-piece outfit on the selected preset person"/>:<div className="outfit-board">{wardrobe.filter(p=>selected.includes(p.id)).map(p=><img key={p.id} src={p.image} alt={p.name}/>)}{!selected.length&&<p>Select a piece to begin your look.</p>}</div>}<p className="fine">{isReference(selected)?'Generated five-piece reference look.':'Your selected pieces, together.'} Custom combinations use a flatlay board; live outfit generation is not connected.</p></div><div><p className="eyebrow">COMPLETE THE LOOK · {selected.length} / 5 PIECES</p>{wardrobe.map((p,index)=><div className="outfit-item" key={p.id}><img src={p.image} alt={p.name}/><div><label><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(s=>s.includes(p.id)?s.filter(id=>id!==p.id):[...s,p.id])}/>{p.name}</label><small>{money(p.price)}</small><select aria-label={`Swap ${p.name}`} value={p.id} onChange={e=>{const next=products.find(q=>q.id===e.target.value)!;setWardrobe(w=>w.map((q,i)=>i===index?next:q));setSelected(ids=>ids.includes(p.id)?ids.map(id=>id===p.id?next.id:id):ids);setNotice(`${next.name} added to your outfit selection`)}}>{products.filter(q=>q.id===p.id||(!wardrobe.some(w=>w.id===q.id)&&(index===0?q.category==='Outerwear':index===1?['Shirts','Tops','Knitwear','Dresses'].includes(q.category):index===2?q.category==='Bottoms':index===3?q.category==='Shoes':q.category==='Accessories'))).map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select><select aria-label={`Size for ${p.name}`} value={sizes[p.id]||''} onChange={e=>setSizes({...sizes,[p.id]:e.target.value})}><option value="">Choose size</option>{p.sizes.map(s=><option key={s}>{s}</option>)}</select></div></div>)}<strong className="outfit-total">Your selection · {money(wardrobe.filter(p=>selected.includes(p.id)).reduce((n,p)=>n+p.price,0))}</strong><button className="primary full" disabled={!selected.length} onClick={()=>{if(selected.some(id=>!sizes[id])){setNotice('Choose a size for each selected piece.');return}onBag(selected.map(id=>({id,size:sizes[id]})));setNotice('Selected pieces added to your local bag.')}}>Add selected pieces to bag</button></div></div>
 <div className="save-look"><input aria-label="Look name" value={name} onChange={e=>setName(e.target.value)} maxLength={60}/><button className="secondary" disabled={!name.trim()||!selected.length} onClick={()=>{persist([...looks,{id:Date.now(),name:name.trim(),items:selected,person:lookPerson}]);setNotice('Look saved. Find it under Saved looks or My Account.')}}>Save this look</button></div><p className="fine">Each brand curates the stylist’s appearance, personality, voice, approved assortment, and styling rules for its audience. This is a fictional brand persona, not a real creative director. Curated local suggestions respond to occasion keywords. No live AI service, weather, calendar, or wardrobe access. Outfit building and styling are roadmap previews.</p></>}{notice&&<p role="status" className="stylist-answer">{notice}</p>}</div>
}
