import {useState,useRef,useEffect} from 'react';
import {Link} from 'react-router';
import {Microphone,SpeakerHigh,Stop,Waveform,SlidersHorizontal,Play,PaperPlaneTilt} from '@phosphor-icons/react';
import {products} from './data';import type {Product} from './data';
import {emptyBrief,understand,selectPieces,completePieces} from './stylist-conversation';
import {useStylistVoice} from './useStylistVoice';
import CompareLooks from './CompareLooks';import CompleteLook from './CompleteLook';
import './voice-stylist.css';
import {stylistSpeech,type StylistSpeechKey} from './stylist-speech';
const greeting=stylistSpeech.greeting;
const personalities=[{id:'studio',name:'Creative studio',detail:'Considered. Confident. Refined.'},{id:'advisor',name:'Personal advisor',detail:'Warm. Curious. Approachable.'},{id:'editorial',name:'Editorial voice',detail:'Expressive. Fashion forward.'}];
export default function VoiceStylist({onBag,onProduct}:{onBag:(items:{id:string;size:string}[])=>void;onProduct?:()=>void}){
 const [brief,setBrief]=useState({...emptyBrief}),[tone,setTone]=useState('studio'),[started,setStarted]=useState(false),[text,setText]=useState(''),[transcript,setTranscript]=useState<{who:string;text:string}[]>([{who:'stylist',text:greeting}]),[choices,setChoices]=useState(['A wedding','An evening out','A getaway','Everyday']),[pieces,setPieces]=useState<Product[]>([]),[offset,setOffset]=useState(0),[mode,setMode]=useState<'discover'|'compare'|'outfit'>('discover'),[anchor,setAnchor]=useState<Product|null>(null),[brand,setBrand]=useState(false),[tour,setTour]=useState(false);
 const [mobileView,setMobileView]=useState<'talk'|'edit'>('talk');const layout=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(window.matchMedia('(max-width:700px)').matches&&started)layout.current?.scrollIntoView({behavior:'smooth',block:'start'})},[mobileView]);
 const [lastSpeech,setLastSpeech]=useState<StylistSpeechKey>('greeting');
 const last=transcript.filter(x=>x.who==='stylist').at(-1)?.text||greeting;const thread=useRef<HTMLDivElement>(null);const voice=useStylistVoice(respond);
 useEffect(()=>{thread.current?.scrollTo({top:thread.current.scrollHeight,behavior:'smooth'})},[transcript.length]);
 function answer(_message:string,next:string[],speech:StylistSpeechKey){setTranscript(t=>[...t,{who:'stylist',text:stylistSpeech[speech]}]);setChoices(next);setLastSpeech(speech);voice.say(speech,true)}
 function respond(value:string){if(!value.trim())return;setStarted(true);setText('');setTranscript(t=>[...t,{who:'you',text:value}]);const s=value.toLowerCase();
 if(/start (over|again)|reset/.test(s)){setBrief({...emptyBrief});setPieces([]);setMobileView('talk');setMode('discover');setOffset(0);answer('A fresh start. What are we dressing for?',['A wedding','Work','A getaway','An evening out'],'reset');return}
 if(/compare|side.by.side|two looks/.test(s)&&pieces.length>=2){setMode('compare');setMobileView('edit');answer('Let’s put these first two pieces side by side. With your profile saved, you’ll see them on you. Which one feels more like you?',['Build a look with the first','Build a look with the second','Show other options'],'compare');return}
 if(/complete|put.*look|build.*look|finish.*look/.test(s)&&pieces.length){const p=/second/.test(s)?pieces[1]||pieces[0]:pieces[0];setAnchor(p);setMode('outfit');setMobileView('edit');answer('Let’s build around '+p.name+'. I’ve added complementary categories from the same collection. You can swap any piece, choose sizes, and add the look to your demo bag.',['Compare these two','Show other options','Start over'],'build');return}
 const next=understand(value,brief);setBrief(next);setMode('discover');
 if(!next.occasion){answer('Tell me the occasion first—perhaps a wedding, dinner, work, or a getaway?',['A wedding','An evening out','Work','A getaway'],'occasion');return}
 if(!next.direction){answer(next.occasion==='A wedding'?'Lovely. What’s the dress code or mood—formal, understated, or a statement look?':'What feels right for you—relaxed, understated, or a little more of a statement?',['Formal','Understated','Statement','Relaxed'],next.occasion==='A wedding'?'wedding':'mood');return}
 if(!next.category){answer('Would you like to explore dresses, tailored separates, or just the finishing accessories?',['Dresses','Tailored separates','Accessories'],'category');return}
 const more=/other|more options|something else/.test(s);const newOffset=more?offset+4:0;let found=selectPieces(products,next,newOffset);if(!found.length&&more)found=selectPieces(products,next,0);setOffset(found.length&&more?newOffset:0);setPieces(found);setMobileView(found.length?'edit':'talk');
 if(!found.length){answer('I couldn’t find pieces matching that selection in this demo collection. Shall we open up the budget or try another category?',['No budget limit','Dresses','Tailored separates','Start over'],'empty');return}
 const prefix=tone==='advisor'?'I have a few ideas for you. ':tone==='editorial'?'Let’s give this look a point of view. ':'Here’s a considered starting point. ';
 answer(prefix+'These pieces are from the store’s collection'+(next.budget!==null?`, each under $${next.budget}. `:'. ')+(found.length>1?'Would you like to compare the first two on you, or build a complete look?':'Shall we build a complete look around this piece?'),[...(found.length>1?['Compare these two']:[]),'Build a look with the first','Show other options'],found.length>1?'results':'single');
 }
 return <div className="voice-stylist"><div className="voice-heading"><div><p className="eyebrow">SPREEAI · AI STYLIST</p><h2>Good style starts <br/>with a conversation.</h2><p>The attention of an in-store stylist. Wherever you shop.</p></div><button className="voice-tour-link" onClick={()=>{voice.stop();setTour(!tour)}}><Play size={15}/>How it works</button></div>
 <div className="voice-brand-strip"><span><i/>Your brand. Your voice. Your point of view.</span><button onClick={()=>setBrand(!brand)} aria-expanded={brand}><SlidersHorizontal size={16}/>Explore brand voices</button></div>
 {brand&&<section className="voice-brand-panel"><h3>A familiar voice. An unmistakable brand.</h3><p>A brand can choose its creative director, a licensed creator or celebrity voice, or an original persona—and define the tone, styling guidance, and assortment.</p><div className="voice-personalities">{personalities.map(p=><button key={p.id} aria-pressed={tone===p.id} onClick={()=>{setTone(p.id);voice.say(p.id as StylistSpeechKey,true)}}><strong>{p.name}</strong><small>{p.detail}</small><span>Listen to this style</span></button>)}</div><p className="voice-demo-note">Demo voice: Celine · Generated speech. These three examples explore different brand tones using the same voice. A connected service can support your authorized custom voice and live conversation.</p></section>}
 {tour&&<section className="voice-walkthrough"><div><p className="eyebrow">A SHORT INTRODUCTION</p><h3>Speak. Discover. See yourself.</h3><p>Tell the stylist your occasion and preferences. Explore real pieces, compare two on your profile, then build a look and choose your sizes.</p><button className="text-link" onClick={()=>setTour(false)}>Back to your conversation</button></div><video controls playsInline preload="metadata" aria-label="AI Stylist interactive experience walkthrough"><source src="/spreeai-always-on-demo/online/media/voice-stylist-walkthrough.mp4" type="video/mp4"/><track kind="captions" src="/spreeai-always-on-demo/online/media/voice-stylist-walkthrough.vtt" srcLang="en" label="English"/></video></section>}
 <div className="voice-mobile-tabs" ref={layout} aria-label="Stylist views"><button aria-pressed={mobileView==='talk'} onClick={()=>setMobileView('talk')}>Conversation</button><button aria-pressed={mobileView==='edit'} onClick={()=>setMobileView('edit')}>Your edit{pieces.length?` · ${pieces.length}`:''}</button></div>
 <div className="voice-layout" data-mobile-view={mobileView}><section className="voice-conversation"><div className={'voice-orb '+(voice.speaking?'is-speaking':voice.listening?'is-listening':'')} aria-hidden="true"><Waveform size={52} weight="thin"/></div><span className="voice-presence">{voice.listening?'Listening to you':voice.speaking?'Your stylist is speaking':'Your personal stylist'}</span><h3>{!started?'Let’s find your next look.':'I’m here. Tell me more.'}</h3><div className="voice-current" aria-live="polite">{last}</div><div className="voice-main-actions">{!started?<button className="voice-start" onClick={()=>{setStarted(true);voice.say('greeting',true)}}><SpeakerHigh size={19}/>Start conversation</button>:<button className={'voice-start '+(voice.listening?'listening':'')} onClick={voice.listen}><Microphone size={19}/>{voice.listening?'Finish speaking':'Tap to speak'}</button>}<button className="voice-audio-control" aria-label={voice.speaking?'Stop speaking':'Hear stylist reply'} onClick={()=>voice.speaking?voice.stop():voice.say(lastSpeech,true)}>{voice.speaking?<Stop size={18}/>:<SpeakerHigh size={18}/>}</button></div><p className="voice-mic-note">{voice.canListen?'Tap to speak when you’re ready. Your browser may process audio using its speech service.':'Voice input isn’t available in this browser. Choose a suggestion or type—spoken replies are available where supported.'}</p>{voice.issue&&<p className="voice-issue" role="status">{voice.issue}</p>}<div className="voice-suggestions">{choices.map(c=><button key={c} onClick={()=>respond(c)}>{c}</button>)}</div><form className="voice-reply" onSubmit={e=>{e.preventDefault();respond(text)}}><input aria-label="Reply to your stylist" value={text} onChange={e=>setText(e.target.value)} maxLength={300} placeholder="Or type naturally…"/><button aria-label="Send reply" disabled={!text.trim()}><PaperPlaneTilt size={19}/></button></form><details className="voice-transcript"><summary>Your conversation</summary><div ref={thread}>{transcript.map((m,i)=><p key={i}><strong>{m.who==='you'?'You':'Stylist'}</strong>{m.text}</p>)}</div></details></section>
 <section className="voice-results"><div className="voice-results-heading"><div><p className="eyebrow">YOUR EDIT, TAKING SHAPE</p><h3>{mode==='compare'?'Two perspectives. Your choice.':mode==='outfit'?'Let’s put it together.':pieces.length?'Selected for the conversation.':'The collection meets your plans.'}</h3></div>{pieces.length>0&&mode!=='discover'&&<button className="text-link" onClick={()=>setMode('discover')}>Back to pieces</button>}</div>{brief.occasion&&<div className="voice-brief">{[brief.occasion,brief.direction,brief.category,brief.budget!==null?`Under $${brief.budget} per piece`:''].filter(Boolean).map(v=><span key={v}>{v}</span>)}</div>}
 {pieces.length>0&&mode==='discover'&&<div className="voice-edit-actions">{pieces.length>1&&<button onClick={()=>respond('Compare these two')}>Compare two looks</button>}<button onClick={()=>setMobileView('talk')} className="voice-return-talk">Refine with your stylist</button></div>}
 {mode==='compare'?<CompareLooks key={pieces.map(p=>p.id).join('|')} initial={pieces.slice(0,2).map(p=>p.id)}/>:mode==='outfit'&&anchor?<CompleteLook key={anchor.id} product={anchor} initialProducts={completePieces(products,anchor,brief)} onBag={onBag}/>:pieces.length?<div className="voice-product-grid">{pieces.map((p,i)=><article key={p.id}><Link onClick={onProduct} to={`/product/${p.id}`}><img src={p.image} alt={p.name}/></Link><small>0{i+1} · {p.category}</small><Link onClick={onProduct} to={`/product/${p.id}`}><h4>{p.name}</h4></Link><p>{p.priceLabel}</p><button className="text-link" onClick={()=>{setAnchor(p);setMode('outfit');setMobileView('edit');answer('Let’s make '+p.name+' the starting point. Explore the pieces alongside it and choose your sizes.',['Compare these two','Show other options','Start over'],'build')}}>Build around this piece</button></article>)}</div>:<div className="voice-empty"><div className="voice-editorial-images">{products.filter(p=>p.category==='Dresses').slice(0,2).map(p=><img key={p.id} src={p.image} alt={p.name}/>)}</div><h4>A wedding. A weekend. A whole new mood.</h4><p>Tell us what’s on your calendar. We’ll ask a few thoughtful questions, then bring the collection into your conversation.</p><span>Real catalog pieces · Personal try-on · Side-by-side comparison</span></div>}
 <p className="voice-results-note">Catalog-led demo · Suggestions are curated, not a live AI consultation. Prices and available sizes come from the connected collection.</p></section></div></div>
}
