const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu?.setAttribute('aria-expanded','false');nav?.classList.remove('open');}});
const moments={discover:['01','Recommendations become personal.','Your brand curates the selection. Eligible recommendations can show the shopper in those pieces, right where they already discover what’s next.'],consider:['02','A gallery with another perspective.','Product and model photography lead. The shopper’s visualization follows naturally, with fit guidance beside size selection and comparison within reach.'],complete:['03','The rest of the look comes together.','Outfit builder begins with the garment they are already considering. Your brand curates combinations, supported pieces and the route to the bag.'],return:['04','One profile. Fewer repeated inputs.','With permission, the shopper’s saved profile can be reused when they return. They can edit or remove it through their account.']};
const tabs=[...document.querySelectorAll('[data-moment]')];tabs.forEach((b,i)=>{b.addEventListener('click',()=>{tabs.forEach(x=>x.setAttribute('aria-selected',String(x===b)));const d=moments[b.dataset.moment];document.querySelector('.journey-number').textContent=d[0];document.querySelector('#moment-copy h3').textContent=d[1];document.querySelector('#moment-copy p').textContent=d[2];});b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[n].focus();tabs[n].click();}});});
let brief='';document.querySelector('#scope-form')?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),features=data.getAll('feature'),status=document.querySelector('#scope-status');if(!features.length){status.textContent='Choose at least one experience to create your brief.';return;}brief=`SPREEAI Always On discussion brief\n\nFirst surface: ${data.get('surface')}\nExperiences: ${features.join(', ')}\n\nNext discussion: current SDK and account system; eligible categories; profile and consent; brand direction; feature availability; pilot goals and measurement.\n\nThis is a conversation brief, not an activation or a delivery commitment.\n`;const result=document.querySelector('#scope-result');result.hidden=false;result.querySelector('p').textContent=brief;status.textContent='Your brief is ready. Nothing has been sent.';result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});});
document.querySelector('#download-scope')?.addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([brief],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='spreeai-always-on-discussion-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.querySelectorAll('video').forEach(v=>{v.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause()}));});
// Keep films expanded. Attempt audible playback only while a film is in view;
// browsers that require interaction receive a muted fallback and an explicit sound control.
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const filmObserver=new IntersectionObserver(entries=>entries.forEach(async entry=>{const v=entry.target;if(!entry.isIntersecting){v.pause();return;}if(reduceMotion)return;try{await v.play();}catch{v.muted=true;try{await v.play();}catch{}const figure=v.closest('figure');if(!figure.querySelector('.sound-enable')){const b=document.createElement('button');b.className='sound-enable';b.type='button';b.textContent='Turn sound on';b.addEventListener('click',()=>{v.muted=false;v.play().catch(()=>{});b.remove();});figure.append(b);}}}),{threshold:.65});
document.querySelectorAll('video').forEach(v=>filmObserver.observe(v));
